name:                error-or
version:             0.1.0.0
synopsis:            Composable, hierarchical errors.
description:         An Applicative Functor with error accumulation. Built in tree like error type
                     meant for gathering and reporting errors to users.
homepage:            https://github.com/luntain/error-or#readme
license:             BSD3
author:              Kamil Dworakowski
maintainer:          kamil@dworakowski.name
copyright:           2020 Kamil Dworakowski
category:            data,library
extra-source-files:
- README.md

tested-with: GHC==8.0.1, GHC==8.2.2, GHC==8.8.1, GHC==8.8.3, GHC==8.10.2

dependencies:
  - base >= 4.9 && < 5 # Need base 4.9 due to Data.Semigroup and MonadFail
  - text
  - containers

library:
  source-dirs:      src
